# Generated by Django 3.2.8 on 2021-10-31 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='light_1',
        ),
    ]
